config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins
  get 'welcome/index'
  root 'welcome#index'

  get 'edit' => 'registrations#edit'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"
  get 'mypins' => 'pins#mypins'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    validates :photo, presence:true
    validates :description, presence:true

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  
  def pinsof
    @user_id = params[:user_id] 
    @user = User.find(@user_id)
    @pins = @user.pins
  end

  def mypins
    @pins = current_user.pins
  end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteres</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.js"> 
        </script>


    </head>

  <body>

    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


     <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :name, "Nombre" %>
      <%= form.text_field :name, :class => 'form-control', :placeholder => "Nombre del Pin" %>
    </div>  
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :photo, "Foto" %>
      <%= form.text_field :photo, :class => 'form-control', :placeholder => "Url de la foto" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :description, "Descripción" %>
      <%= form.text_area :description, :class => 'form-control', :rows => "10", :cols => "30" %>
    </div>
  </div>

  

  <div class="actions">
    <%= form.submit "Crear", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Editing Pin</h1>
            <%= render 'form', pin: @pin %>
        </div>
    </div>

    <%= link_to 'Show', @pin %> |
    <%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>
<div class="container">
 
      <% @pins.each do |pin| %>
        
        <div class="col-md-3"> 
          <div class="thumbnail">
            <%= pin.name %>
            <%= image_tag(pin.photo, :class => 'img-responsive') %>
            <%= pin.description %>
            <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              <%= link_to 'Show', pin, :class => 'btn' %>
              <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
              <% if user_signed_in? %>
              <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
              <% end %>
            </div> 
          </div>  
       </div>
      <% end %>
   

  <br>
  <% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
  <% end %>
  </div>

app/views/pins/mypins.html.erb
<div class="container">
 
      <% @pins.each do |pin| %>
        
        <div class="col-md-3"> 
          <div class="thumbnail">
            <%= pin.name %>
            <%= image_tag(pin.photo, :class => 'img-responsive') %>
            <%= pin.description %>
            <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              <%= link_to 'Show', pin, :class => 'btn' %>
              <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
              <% if user_signed_in? %>
              <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
              <% end %>
            </div> 
          </div>  
       </div>
      <% end %>

      <br>
      <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path %>
      <% end %>
      </div>

app/views/pins/new.html.erb
<div class="container">
    <h1>Agregar nuevo Pin</h1>
    <div class="row">
        <div class="col-md-6">
        <%= render 'form', pin: @pin %>
        </div>

        <p><%= link_to 'Back', pins_path %></p>
    </div>
</div>

app/views/pins/pinsof.html.erb
<%= @user_id %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style=> 'width:500px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

<%= link_to "Mas Pins del mismo usuario", pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="<%= root_path %>">Mi Pinterest</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li>
      <a class="nav-link" href="#">Nosotros <span class="sr-only">(current)</span></a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="<%= mypins_path %>"> Mis Pins</a>
    </li>
    
    <li class="nav-item">
    <a class="nav-link" href="<%= pins_path %>">Pins</a>
  </li>

    
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Dropdown
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
 </ul>

 <ul class="navbar-nav navbar-right">
  <% if current_user.nil? %>
    <li class="nav-item ">
    <a class="nav-link " href="<%= new_user_session_path %>">Ingreso</a>
    </li>
  
    <li class="nav-item ">
    <a class="nav-link " href="<%= new_user_registration_path %>">Registro</a>
    </li>
  <% else %>
    <li class="nav-item ">
    <a class="nav-link " href="<%= destroy_user_session_path %>" data-method="DELETE">Salir</a>
    </li>
  <% end %>
  </ul>
  
</div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
<div class="container">
  <h1 class="display-4">Título</h1>
  <p class="lead">Otro título.</p>
  <a class="btn btn-primary btn-lg" href="http://en1mes.com" role="button">En1Mes</a>
   
</div>  
</div>
<div class="container">
<div class="row">
<div class="col-md-4">
  <div class="page-header">
    <h2 style="display:inline">Example page </h2>
    <span class="label placeholder">New</span>
  </div>
 <a href="http://en1mes.com" target="_blank"> En1mes en otra página</a>
 <p class="titulos"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro, fuga ipsum repudiandae reiciendis architecto quos iste eius debitis quia mollitia quasi quidem maiores repellat sint iusto sequi. Nobis, facilis corrupti!
 </p> 
</div>
<div class="col-md-4">
    <h2> Subtítulos 2</h2>
    <p class="titulos"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro, fuga ipsum repudiandae reiciendis architecto quos iste eius debitis quia mollitia quasi quidem maiores repellat sint iusto sequi. Nobis, facilis corrupti!
    </p> 
   </div>
<div class="col-md-4">
    <h3>Sub subtítulo</h3>
    <p class="titulos"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro, fuga ipsum repudiandae reiciendis architecto quos iste eius debitis quia mollitia quasi quidem maiores repellat sint iusto sequi. Nobis, facilis corrupti!
    </p> 
    <a href="http://en1mes.com"> 
    <img src="https://en1mes.com/assets/logo-5d8021b65a5944316da34b544b012157.png" alt="logo en 1 mes">
    </a>
    <hr>
    <br>

    <img src="http://okautomoviles.com/wp-content/uploads/2017/11/Conoce-el-Tesla-Roadster-el-auto-deportivo-eléctrico-más-veloz-del-mundo-750x445.jpg" class="img-fluid" alt="Responsive image">
    <ol>
      <li>Item 1</li>
      <li>Item 2</li>
      <li>Item 3</li>
    </ol>

</div>
</div>
</div>